name: UVB-76 BOT Windows 

on:
  schedule:
    - cron: "1 */6 * * *"  # Toutes les 6 heures
  workflow_dispatch:       # Permet de déclencher manuellement ce workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify Node.js version here

    - name: log node.js
      run: npm init -y
 
    - name: Install dependencies
      run: |
        npm install discord.js dotenv axios
        npm install axios cheerio xml2js
        npm install node-fetch
        npm install xml2js
      
    - name: Run Discord Bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        node bot.js
